[book]
title = "Mechanizing the Nano-P4 specification with P4-SpecTec"
authors = ["Haechan Kwon"]
language = "en"

[output.html]
additional-css = ["theme/catppuccin.css", "theme/spectec.css", "theme/p4.css"]

[preprocessor.spectec-highlight]
command = "mdbook-spectec-highlight/target/debug/mdbook-spectec-highlight"

[preprocessor.p4-highlight]
command = "mdbook-p4-highlight/target/debug/mdbook-p4-highlight"
